### ISSUE TITLE
Create custom theme

### ISSUE THREAD

**Issue by szgabsz91** [szgabsz91/iit-szg#13]
The custom theme should contain SCSS variables and custom colors.

**Comment by szgabsz91** [comment]
An old custom theme SCSS version:

```scss
@import '../node_modules/highlight.js/styles/github.css';

@import '../node_modules/@angular2-material/button/button.css';
@import '../node_modules/@angular2-material/card/card.css';
@import '../node_modules/@angular2-material/sidenav/sidenav.css';
@import '../node_modules/@angular2-material/toolbar/toolbar.css';

@import url(https://fonts.googleapis.com/css?family=Material+Icons);
@import url(https://fonts.googleapis.com/css?family=Roboto);

$primary_color: #153d66;
$primary_color_light: lighten($primary_color, 35%);
$primary_color_lighter: lighten($primary_color_light, 10%);
$primary_color_lightest: lighten($primary_color_lighter, 20%);
$secondary_color: white;
$tertiary_color: #fafafa;

html, body {
    height: 100%;
}

body {
    margin: 0;
    font-family: Roboto !important;
    background: $tertiary_color;
}

// Loading Icon

.loading {
    position: relative;
    width: calc(100% - 120px);
    height: 100%;
    text-align: center;
}

.loading img {
    position: absolute;
    top: 0;
    bottom: 0;
    margin: auto;
}

// Sidenav

md-sidenav-layout {
    min-height: 100%;
}

md-sidenav {
    min-width: 250px !important;
    text-align: center;
    background-color: $primary_color_light !important;
}

md-sidenav .logo {
    background: $primary_color;
    height: 64px;
    display: flex;
    align-items: center;
    justify-content: center;
    box-shadow: 0 3px 0 rgba(0, 0, 0, 0.2);
    margin-bottom: 32px;
}

md-sidenav .logo img:hover {
    filter: drop-shadow(1px 0 1px $primary_color_lighter) drop-shadow(-1px 0 1px $primary_color_lighter) drop-shadow(0 -1px 1px $primary_color_lighter) drop-shadow(0 1px 1px $primary_color_lighter);
}

md-sidenav a[md-button] {
    color: $secondary_color;
    width: 90%;
}

md-sidenav a[md-button]:hover {
    background-color: $primary_color_lighter;
}

md-sidenav .course {
    margin-bottom: 12px;
}

md-sidenav .course > a[md-button] {
    font-size: 20px !important;
    padding: 4px 0;
}

md-sidenav .course > .practice > a[md-button] {
    font-size: 16px !important;
}

// Toolbar

md-toolbar {
    background: $primary_color !important;
    box-shadow: 0 3px 2px rgba(0, 0, 0, 0.2);
}

md-toolbar button {
    padding: 0 14px 0 14px;
}

md-toolbar button .material-icons {
    color: $secondary_color;
}

// Footer

footer {
    margin-bottom: 24px;
}

footer,
footer a {
    text-align: center;
    color: #888;
    font-size: 14px;
}

footer a {
    text-decoration: underline;
}

footer a:hover {
    text-decoration: none;
}

// Cards

md-card {
    box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 1px 5px 0 rgba(0, 0, 0, 0.12), 0 3px 1px -2px rgba(0, 0, 0, 0.2) !important;
    line-height: 1.5;
}

md-sidenav-layout md-card {
    width: 90%;
    margin: 50px auto;
}

// Lists

.md-list-item:hover {
    cursor: pointer;
    background: $primary_color_lightest !important;
}

.md-list-item h4 {
    font-weight: bold !important;
    margin-bottom: 8px !important;
}

.md-list-item p {
    color: #888;
}

// Tables

table {
    margin-bottom: 24px;
}

table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
    padding: 4px;
}

// Google Spreadsheet IFrame

iframe {
    display: block;
    width: 98%;
    margin: 48px auto;
    min-height: 500px;
}
```
